		<?php list_css ("<link rel=\"stylesheet\" href=\"/_models/_blocks/_block_main/_style_block.css\">"); ?>
		
		<div class="_block_main">
			<div class="centerbox stiker">
				<h2><span>стеклоизделия</span> <span>фурнитура</span>
				<br /><span>стеклоконструкции</span> <span>витражи</span>
				</h2>
				<p>стекло декоративное, зеркала, багеты, стеклоблоки, душевые кабины, стеклянные перегородки и двери, столы из стекла, шкафы-купе, фотопечать по стеклу, матирование стекла, закаливание стекла, резка стекла и многое другое</p>
			</div>
		</div>