<?php list_css ("<link rel=\"stylesheet\" href=\"/models/_miniblk-N/_miniblk-card_v1/_miniblk-card_v1.css\">"); ?>

	<div class="miniblk-card_v1v1">
		<img src="/models/_miniblk-N/_miniblk-card_v1/_img-N/tarakan.1_0.png" alt="Таракан, знак">
		<h3 class="head">Выведение насекомых
		</h3>
		<div class="text"><strong>Выведение муравьев, выведение тараканов, выведение блох, вшей, выведение клещей, выведение мух, комаров, ос, шершней, выведение клопов, пауков</strong> (дезинсекция) ...
		</div>
	</div>
		
	<div class="miniblk-card_v1v1">
		<img src="/models/_miniblk-N/_miniblk-card_v1/_img-N/krisa.1_0.png" alt="Крыса, знак">
		<h3 class="head">Выведение крыс, мышей
		</h3>
		<div class="text">Выведение крыс, мышей (дератизация), выведение кротов, капканы, липкие ловушки, звуковые отпугиватели, отравленные приманки, опыление, газация ...
		</div>
	</div>

	<div class="miniblk-card_v1v1">
		<img src="/models/_miniblk-N/_miniblk-card_v1/_img-N/clining.1_0.png" alt="Дезодорация, знак">
		<h3 class="head">Дезодорация и клининг
		</h3>
		<div class="text">Удаление запаха гнили, фекалий, горелых предметов, озонирование воздуха, распыление дезодоранта, физическая и химическая обработкой отходов, нечистот ...
		</div>
	</div>	
			
	<div class="miniblk-card_v1v1">
		<img src="/models/_miniblk-N/_miniblk-card_v1/_img-N/disinfection.2_0.png" alt="Дезинфекция дома, знак">
		<h3 class="head">Антимикробная обработка
		</h3>
		<div class="text">Антимикробная, антибактериальная обработка помещений (дезинфекция): уничтожение микробов в помещении, удаление плесени, обработка вентиляции, кварцевание ...
		</div>
	</div>	
		
	<div class="miniblk-card_v1v1">
		<img src="/models/_miniblk-N/_miniblk-card_v1/_img-N/truck.1_0.png" alt="Грузовик, знак">
		<h3 class="head">Обработка транспорта
		</h3>
		<div class="text">Справки, договоры, акты. Санитарная обработка грузового, пассажирского, медицинского, ритуального транспорта, уничтожение микробов (дезинфекция) ...
		</div>
	</div>			
		
	<div class="miniblk-card_v1v1">
		<img src="/models/_miniblk-N/_miniblk-card_v1/_img-N/pugach.1_0.png" alt="Отпугивание собак, знак">
		<h3 class="head">Продажа отпугивателей 
		</h3>
		<div class="text">Отпугиватели клещей, комаров, уничтожители комаров, отпугиватели собак, отпугиватели птиц, отпугиватели мышей, крыс, отпугиватели кротов, ловушки для мышей ...
		</div>
	</div>	
		
	<div class="miniblk-card_v1v1">
		<img src="/models/_miniblk-N/_miniblk-card_v1/_img-N/home.1_0.png" alt="Дом, знак">
		<h3 class="head">Обработка квартир, домов 
		</h3>
		<div class="text">Выведение насекомых (дезинсекция), удаление плесени,  выведение мышей (дератизация), удаление плесени, дезинфекция погреба ...
		</div>
	</div>	
			
	<div class="miniblk-card_v1v1">
		<img src="/models/_miniblk-N/_miniblk-card_v1/_img-N/salon.1_0.png" alt="Салон кафе, знак">
		<h3 class="head">Обработка кафе, салонов 
		</h3>
		<div class="text">Выведение насекомых (дезинсекция), антимикробная обработка (дезинфекция), выведение мышей (дератизация), обработка вентиляции, кварцевание, удаление плесени
		</div>
	</div>	
			
	<div class="miniblk-card_v1v1">
		<img src="/models/_miniblk-N/_miniblk-card_v1/_img-N/grass.1_0.png" alt="Трава, знак">
		<h3 class="head">Обработка участков 
		</h3>
		<div class="text">Уничтожение крысиных клещей на участках, территориях, уничтожение муравьев, выведение крыс, мышей, выведение кротов, установка отпугивателей, ловушек ...
		</div>
	</div>	
			
	<div class="miniblk-card_v1v1">
		<img src="/models/_miniblk-N/_miniblk-card_v1/_img-N/company.1_0.png" alt="Компания здания, знак">
		<h3 class="head">Обработка предприятий 
		</h3>
		<div class="text">Выведение насекомых (дезинсекция), антимикробная обработка (дезинфекция), выведение мышей (дератизация), обработка вентиляции, удаление плесени ...
		</div>
	</div>
</div>