
<?php $Active=""; $URIlink ="обработка"; ?>

<?php list_css("<link rel=\"stylesheet\" href=\"/_models/_menus/_menu_main/_style_menu.css\">"); ?>

	<ul class="_menu_main">
		<li>
<a class="menubutt activebutt" href="/">Основная</a>
		</li>
		<li>
<a class="menubutt" href="/imagazin.php">Услуги</a>
		</li>
		<li>
<a class="menubutt" href="/iprodukcia.php">Витражи</a>
		</li>
		<li>
<a class="menubutt" href="/uslugi.php">Мастерская</a>
		</li>
		<li>
<a class="menubutt" href="/galereya.php">Галерея</a>
		</li>
		<li>
<a class="menubutt" href="/kontakti.php">Контакты</a>
		</li>
	</ul>
		</tbody></table>


