
<?php list_css ("<link rel=\"stylesheet\" href=\"/_models/_pages/_page_index/_style_main.css\">"); ?>

<main class="_page_main">

	<div class="widthbox">
		<div class="centerbox clearfix">
		
<?php include ($_SERVER['DOCUMENT_ROOT']."/_models/_blocks/_block_stiker/_block.inc"); ?>

		</div>
	</div>

	<div class="widthbox">
		<div class="centerbox clearfix">
			<div class="caption_cont">Все услуги</div>

<?php include ($_SERVER['DOCUMENT_ROOT']."/_models/_blocks/_block_card/_block.inc"); ?>
		
		</div>
	</div>

	<div class="widthbox widthbox-3">
<?php include ($_SERVER['DOCUMENT_ROOT']."--/_models/_blocks/_block_fon/_block.inc"); ?>
	</div>
	
	<div class="content4">
		<div class="boxcenter clearfix">
			
			<div class="microbox">
			<img src="/models/_microbox.1_0/document.1_0.png" alt="Документы справки, знак">
			<span><b>Комплект документов</b> на проведение дезинфекции</span>
			</div>
			
			<div class="microbox">
			<img src="/models/_microbox.1_0/pdf.1_0.png" alt="Прайст-лист, знак">
			<span><b>Загрузить прайст-лист</b>. Гибкое ценообразование </span>
			</div>
			
			<div class="microbox">
			<img src="/models/_microbox.1_0/sale.2_0.png" alt="Акция, знак">
			<span><b>Акции на услуги!</b> <br />Скидки пенсионерам</span>
			</div>
			
			<div class="microbox">
			<img src="/models/_microbox.1_0/nnov.1_0.png" alt="Нижегородская область, знак">
			<span><b>Нижний Новгород</b> и Нижегородская область</span>
			</div>
			
			<div class="microbox null-margr">
			<img src="/models/_microbox.1_0/rub.2_0.png" alt="Способы оплаты, знак">
			<span><b>Способы оплаты:</b> <br>карта, нал/безнал. рассчет</span>
			</div>
			
		</div>
	</div>

	<div class="content5">
		<div class="boxcenter">
			
			<img class="companis" src="/data/images/_companis/cocacola.1_0.png" alt="Кока Кола, знак">
			<img class="companis" src="/data/images/_companis/cocacola.1_0.png" alt="Кока Кола, знак">
			<img class="companis" src="/data/images/_companis/cocacola.1_0.png" alt="Кока Кола, знак">
			<img class="companis" src="/data/images/_companis/cocacola.1_0.png" alt="Кока Кола, знак">
			<img class="companis" src="/data/images/_companis/cocacola.1_0.png" alt="Кока Кола, знак">
			<img class="companis" src="/data/images/_companis/cocacola.1_0.png" alt="Кока Кола, знак">
			<img class="companis" src="/data/images/_companis/cocacola.1_0.png" alt="Кока Кола, знак">
			<img class="companis" src="/data/images/_companis/cocacola.1_0.png" alt="Кока Кола, знак">
			<img class="companis" src="/data/images/_companis/cocacola.1_0.png" alt="Кока Кола, знак">
			<img class="companis" src="/data/images/_companis/cocacola.1_0.png" alt="Кока Кола, знак">
		</div>
	</div>

</main>