
<?php list_css ("<link rel=\"stylesheet\" href=\"/_models/_pages/_page_index/_style_header.css\">"); ?>

<header class="str widthbox">

	<div class="widthbox">
		<div class="centerbox clearfix">
			<div class="logobox">
<?php include ($_SERVER['DOCUMENT_ROOT']."/_data/_logos/_logo.inc"); ?>
			</div>
			<div class="contacts" >
				<div class="address">
			<img src="/_models/_pages/_imgs_icon/_icon_location.png" alt="Локация">
			Казанское шоссе
			<br>д.14, корп.1 (салон) 
				</div>
			
				<div class="time">
			<img src="/_models/_pages/_imgs_icon/_icon_clock.png" alt="Время работы">
			Пн - Сб: 9:00 - 18:00
			<br>Вс: выходной
				</div>
				<div class="phone">
			<img src="/_models/_pages/_imgs_icon/_icon_phone.png" alt="Телефон">
			+7 (831) 278-18-05
			<br>+7 (909) 297-61-17 
				</div>
			</div>
		</div>
	</div>
	<div class="widthbox">
		<div class="centerbox">
<?php include ($_SERVER['DOCUMENT_ROOT']."/_models/_menus/_menu_main/_menu.inc"); ?>
		</div>
	</div>
	<div class="widthbox">
<?php include ($_SERVER['DOCUMENT_ROOT']."/_models/_blocks/_block_main/_block.inc"); ?>
	</div>
	
</div>