
<?php $Active=""; $URIlink ="обработка"; ?>

<?php list_css("<link rel=\"stylesheet\" href=\"/model01/_menuN/_menu_main/_style_menu.css\">"); ?>

	<ul class="mainmenu-gr">
<li class="button <?php if ($URIlink =="/") {echo $Active;} ?>"><a href="/">Главная</a></li>
<li class="button <?php echo $Active; ?>"><a href="/text/_text.klesch.1_0">Обработка помещений</a></li>
<li class="button <?php echo $Active; ?>"><a href="/">Обработка участков</a></li>
<li class="button <?php echo $Active; ?>"><a href="/">Обработка транспорта</a></li>
<li class="button <?php echo $Active; ?>"><a href="/">Средства защиты</a></li>
<li class="button <?php echo $Active; ?>"><a href="/">Контакты</a></li>
	</ul>


